# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 94a5df3a0a6c79051178fc1ae372ec3308910f08e0a76c79fe6c97495daf6a5f873780ad4826379bb6bf7c4d516e58e75ce2cd6f05efaea321bbead81fd82af6

test:
  secret_key_base: 2c09e9caf3416b7f5e90691d2148ca879e2510c2872683a2871f10e5985acfc136e6f8e0d294e9f681a121ab3c0c4d1ff032068807280c799589ae7bf6df4ef1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
